language: r
warnings_are_errors: true
sudo: required

cache: apt

notifications:
  email:
    on_success: change
    on_failure: change

r_github_packages:
  - jimhester/covr
after_success:
  - Rscript -e 'library(covr);codecov()'
